# Generated by Django 3.2.8 on 2021-10-27 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=50)),
                ('application_date', models.DateField()),
                ('application_status', models.CharField(choices=[('W', 'Waiting for response'), ('rOA', 'Received online assessment'), ('cOA', 'Completed online assessment'), ('rI', 'Received interview'), ('cI', 'Completed interview'), ('O', 'Received offer'), ('R', 'Rejected'), ('G', 'Ghosted')], default='N', max_length=30)),
            ],
        ),
    ]
